# Generated by Django 4.0.6 on 2022-07-06 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Flat', 'Квартира/Дом'), ('Hotel', 'Отель'), ('Room', 'Комната/Номер')], default='', max_length=50, verbose_name='Тип')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('name', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Название')),
                ('is_full', models.BooleanField(default=False, verbose_name='Заполненно?')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2022, 7, 6))),
                ('end_date', models.DateField(default=datetime.date(2022, 7, 6))),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='main_app.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.apartment')),
            ],
        ),
    ]
