# Generated by Django 4.0.6 on 2022-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='hotel_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='hotel_id'),
        ),
    ]
