# Generated by Django 4.0.6 on 2022-07-09 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_apartment_address_alter_apartment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='cost',
            field=models.IntegerField(default=1, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email хозяина'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email гостя'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 7, 9)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 7, 9)),
        ),
    ]
