# Generated by Django 4.0.6 on 2022-07-26 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_apartment_cost_apartment_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='are_we_intermediary',
            field=models.BooleanField(default=False, verbose_name='Мы посредник?'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner_contacts',
            field=models.TextField(blank=True, default='', verbose_name='Контакты хозяина'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 7, 26)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 7, 26)),
        ),
    ]
